[project]
name = "ardca-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.84",
    "numpy>=2.2.0",
    "pytest>=8.3.4",
    "torch>=2.5.1",
]

[tool.uv.workspace]
members = ["code"]
